name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory to dev
        run: cd dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -sSL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          sudo mv /tmp/tflint /usr/local/bin/tflint

      - name: TFLint
        run: tflint

      - name: Terraform Plan
        run: terraform plan

      - name: Manual Validation
        run: echo "Please verify the plan manually before applying."

      - name: Terraform Apply
        run: terraform apply -auto-approve
